services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}
      POSTGRES_USER: ${POSTGRES_USER:-k8mpatible}
      POSTGRES_DB: ${POSTGRES_DB:-k8mpatible}
    ports:
      - '5432:5432'
