# Default values for k8mpatible-website.
replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/production-9bb4/k8mpatible/website
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
    - host: www.k8mpatible.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: k8mpatible-website
      hosts:
        - k8mpatible.com
        - www.k8mpatible.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env: prod
PGHOST: "postgres"
