apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "k8mpatible-website.fullname" . }}
  labels:
    {{- include "k8mpatible-website.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-store
    kind: ClusterSecretStore
  target:
    name: {{ include "k8mpatible-website.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: "{{ .Values.env }}-password"
    - secretKey: PGPASSWORD
      remoteRef:
        key: "{{ .Values.env }}-password"
    - secretKey: AUTH_SENDGRID_KEY
      remoteRef:
        key: "{{ .Values.env }}-sendgrid-key"
