name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

env:
  REGISTRY: us-central1-docker.pkg.dev
  PROJECT_ID: production-9bb4
  CHART_PATH: ./charts/k8mpatible-website
  RELEASE_NAME: website
  NAMESPACE: production

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/235815295809/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions@production-9bb4.iam.gserviceaccount.com"

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: production
          location: us-central1-a

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Deploy Helm chart
        run: |
          helm upgrade --install ${{ env.RELEASE_NAME }} ${{ env.CHART_PATH }} \
            --namespace ${{ env.NAMESPACE }} \
            --set image.tag=${{ github.sha }} \
            --create-namespace